services:

  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ReverseProxy__Clusters__identity-cluster__Destinations__identity-1__Address: "http://identity-service:8080"
      ReverseProxy__Clusters__account-cluster__Destinations__account-1__Address: "http://account-service:8080"
      ReverseProxy__Clusters__transaction-cluster__Destinations__transaction-1__Address: "http://transaction-service:8080"
      ReverseProxy__Clusters__loan-cluster__Destinations__loan-1__Address: "http://loan-service:8080"
      ReverseProxy__Clusters__notification-cluster__Destinations__notification-1__Address: "http://notification-service:8080"
      ReverseProxy__Clusters__payment-cluster__Destinations__payment-1__Address: "http://payment-service:8080"
